### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by S-Marv**

### CODE REVIEW

**Comment by hergin** [comment]
This passed but technically you should run `npm install nyc --save-dev` command in the repository only once. Not in the github actions file.

**Review by hergin — CHANGES_REQUESTED** [review]
Run this in local `npm install nyc --save-dev` and then do the rest.

**Comment by hergin** [comment]
You should run that in codespace, that should be a change in package.json and package.lock.json

**Review by jamisontucker — APPROVED** [review]
Looks good

**Review by hergin — APPROVED** [review]

**Pull request merged**
